server.port=8082
spring.application.name=policy-service

services.user-service.url=http://localhost:8081

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:policydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info